platform :ios, '10.0'

source 'https://github.com/leanhWebsynergies/react-native-podspec'
source 'https://cdn.cocoapods.org/'

target 'MySdk-poc' do
  use_frameworks!
  
  # path to the sdk
  pod 'MySdk-native', :path=> '../MySdk-native'
  
  # If you added this to your private podspec then there is not need for this pod
  pod 'RNFastImage', :git=> 'git@github.com:DylanVann/react-native-fast-image.git', :tag=> 'v8.5.11'
  pod 'react-native-camera', :git=> 'git@github.com:react-native-community/react-native-camera', :tag=> 'v3.4.0'
  pod 'react-native-contacts', :git=> 'git@github.com:rt2zz/react-native-contacts.git'
  pod 'react-native-google-analytics-bridge', :git=> 'git@github.com:idehub/react-native-google-analytics-bridge', :tag=> 'v7.1.0'
  pod 'react-native-image-picker', :git=> 'git@github.com:react-native-community/react-native-image-picker.git', :tag=> 'v1.0.2'
  pod 'react-native-image-resizer', :git=> 'git@github.com:bamlab/react-native-image-resizer.git', :tag=> 'v1.2.2'
  pod 'react-native-randombytes', :git=> 'git@github.com:mvayngrib/react-native-randombytes.git'
  pod 'react-native-sensitive-info', :git=> 'git@github.com:mCodex/react-native-sensitive-info.git'
  pod 'RNCAsyncStorage', :git=> 'git@github.com:react-native-community/react-native-async-storage.git', :tag=> 'v1.5.0'
  pod 'RNCClipboard', :git=> 'git@github.com:react-native-community/clipboard', :tag=> 'v1.5.1'
  pod 'RNDeviceInfo', :git=> 'git@github.com:react-native-community/react-native-device-info.git', :tag=> 'v5.5.8'
  pod 'RNFS', :git=> 'git@github.com:itinance/react-native-fs', :tag=> 'v2.13.3'
  pod 'RNGestureHandler', :git=> 'git@github.com:software-mansion/react-native-gesture-handler', :tag=> '1.6.1'
  pod 'RNGoogleSignin', :git=> 'git@github.com:react-native-community/google-signin.git', :tag=> 'v4.0.3'
  pod 'RNRate', :git=> 'git@github.com:KjellConnelly/react-native-rate.git', :branch => 'master'
  pod 'RNReanimated', :git=> 'git@github.com:kmagiera/react-native-reanimated.git', :tag=> '1.0.0'
  pod 'RNShare', :git=> 'git@github.com:react-native-community/react-native-share.git', :tag=> 'v3.0.0'
  pod 'RNVectorIcons', :git=> 'git@github.com:oblador/react-native-vector-icons.git', :tag=> 'v6.6.0'
  pod 'TouchID', :git=> 'git@github.com:naoufal/react-native-touch-id.git'
  pod 'BVLinearGradient', :git=> 'git@github.com:brentvatne/react-native-linear-gradient.git', :tag=> 'v2.5.4'

  

  target 'MySdk-pocTests' do
    inherit! :search_paths
  end

  target 'MySdk-pocUITests' do
  end

end
