platform :ios, '9.0'

source 'https://github.com/leanhWebsynergies/react-native-podspec'
source 'https://cdn.cocoapods.org/'

target 'MySdk-native' do
  use_frameworks!

  pod 'React'
  pod 'React-Core'
  pod 'ReactCommon'
  pod 'React-CoreModules'
  pod 'FBLazyVector'
  pod 'FBReactNativeSpec'
  pod 'RCTRequired'
  pod 'RCTTypeSafety'
  
  pod 'RNFastImage', :git=> 'git@github.com:DylanVann/react-native-fast-image.git', :tag=> 'v8.5.11'
  
  end
